import { createMustacheMarkdownBlock } from "../../../../builder/mustacheBlock";

const template = [
	"# **`=this.Name`**",
	"",
	"> [!overview]- Overview",
	"General description of this culture, its traits, and identity.",
	"",
	"> [!culture]- Traditions & Customs",
	"Festivals, social norms, etiquette, rites of passage.",
	"",
	"> [!story]- Arts & Expression",
	"Music, dance, theatre, visual arts, literature, architecture.",
	"",
	"> [!misc]- Daily Life",
	"Dress, cuisine, values, everyday practices, taboos.",
	"",
	"> [!History]- History & Origins",
	"Myths & legends; key events; eras & dynasties.",
	"",
	"> [!demographics]- Demographics",
	"Population trends, composition, languages, diaspora.",
	"",
	"> [!Religion]- Belief Systems",
	"Pantheons, rituals, sacred sites, factions/cults.",
	"",
	"> [!government]- Governance & Law",
	"Power structures, rulers, laws/justice, corruption.",
	"",
	"> [!Regions]- External Relations",
	"Neighbors, spread, alliances, rivalries, legacy.",
	"",
	"> [!Notes]- Notes",
	"Catch-all details, to-dos, references.",
	"",
	"> [!Rumors]- Rumors",
	"Whispers, gossip, popular tales.",
	"",
	"> [!Secrets]- Secrets",
	"Hidden truths, forbidden practices, concealed history.",
	"",
	"> [!lore]- Lore",
	"Oral histories, philosophies, enduring legends.",
].join("\n");

export const botiCultureMainContentBlock = createMustacheMarkdownBlock({
	id: "boti.culture.mainContent",
	template,
});
