import type { TLCulture } from "../../../definitions/TerraLogger";

export const createEmptyCulture = (): TLCulture => ({
  _id: '',
  aliases: [],
  architecture: "",
  arts: "",
  base: 0,
  code: '',
  color: '',
  cuisine: "",
  description: '',
  dress: "",
  ethnicGroups: [],
  expansionism: 0,
  government: "",
  id: 0,
  language: "",
  name: '',
  notableFigures: [],
  origins: [],
  pronounced: "",
  region: "",
  religions: [],
  ruralPop: '',
  shield: '',
  tags: [],
  technologyLevel: "",
  theme: "",
  traditions: [],
  type: '',
  urbanPop: '',
  values: [],
});
