import type { DefaultCatalogBundle } from "../../../../generators/defaults";
import type {
	NPCAgeRangeRecord,
	NPCProfileValueRecord,
} from "../../types";

function valueRecords(
	field: NPCProfileValueRecord["field"],
	values: readonly (string | { value: string; weight?: number; ancestryIds?: string[] })[],
): NPCProfileValueRecord[] {
	return values.map((entry, index) => {
		const normalized = typeof entry === "string" ? { value: entry } : entry;
		return {
			id: `default:profile.${field}.${index + 1}`,
			source: "default",
			version: 1,
			enabled: true,
			table: `npc.profile.${field}`,
			field,
			value: normalized.value,
			weight: normalized.weight ?? 1,
			ancestryIds: normalized.ancestryIds,
		};
	});
}

const ancestryIds = {
	human: "default:ancestry.human",
	dragonkin: "default:ancestry.dragonkin",
	dwarf: "default:ancestry.dwarf",
	elf: "default:ancestry.elf",
	gnome: "default:ancestry.gnome",
	goblin: "default:ancestry.goblin",
	giant: "default:ancestry.giant",
	halfling: "default:ancestry.halfling",
	halfElf: "default:ancestry.half-elf",
	lizardfolk: "default:ancestry.lizardfolk",
	orc: "default:ancestry.orc",
	halfOrc: "default:ancestry.half-orc",
	demonkin: "default:ancestry.demonkin",
} as const;

export const npcAgeRangeDefaults: NPCAgeRangeRecord[] = [
	[ancestryIds.human, 18, 80],
	[ancestryIds.dragonkin, 16, 120],
	[ancestryIds.dwarf, 35, 300],
	[ancestryIds.elf, 50, 650],
	[ancestryIds.gnome, 30, 420],
	[ancestryIds.goblin, 14, 60],
	[ancestryIds.giant, 20, 220],
	[ancestryIds.halfling, 20, 140],
	[ancestryIds.halfElf, 20, 180],
	[ancestryIds.lizardfolk, 14, 90],
	[ancestryIds.orc, 16, 85],
	[ancestryIds.halfOrc, 18, 110],
	[ancestryIds.demonkin, 18, 160],
].map(([ancestryId, minimumAge, maximumAge], index) => ({
	id: `default:profile.age-range.${index + 1}`,
	source: "default",
	version: 1,
	enabled: true,
	table: "npc.profile.age-ranges",
	ancestryIds: [String(ancestryId)],
	minimumAge: Number(minimumAge),
	maximumAge: Number(maximumAge),
	weight: 1,
}));

export const npcProfileValueDefaults: NPCProfileValueRecord[] = [
	...valueRecords("nickname", [
		"the Steady",
		"the Keen",
		"the Quiet",
		"the Bold",
		"the Lucky",
		"the Watchful",
		"the Kind",
		"the Swift",
		"the Iron-Willed",
		"the Far-Seeing",
	]),
	...valueRecords("heritage", [
		{ value: "Lowland Human", ancestryIds: [ancestryIds.human] },
		{ value: "Highland Human", ancestryIds: [ancestryIds.human] },
		{ value: "Riverland Human", ancestryIds: [ancestryIds.human] },
		{ value: "Ember-Clan Dragonkin", ancestryIds: [ancestryIds.dragonkin] },
		{ value: "Storm-Clan Dragonkin", ancestryIds: [ancestryIds.dragonkin] },
		{ value: "Stone Dwarf", ancestryIds: [ancestryIds.dwarf] },
		{ value: "Deep Dwarf", ancestryIds: [ancestryIds.dwarf] },
		{ value: "High Elf", ancestryIds: [ancestryIds.elf] },
		{ value: "Wood Elf", ancestryIds: [ancestryIds.elf] },
		{ value: "Rock Gnome", ancestryIds: [ancestryIds.gnome] },
		{ value: "Forest Gnome", ancestryIds: [ancestryIds.gnome] },
		{ value: "Cave Goblin", ancestryIds: [ancestryIds.goblin] },
		{ value: "Hill Goblin", ancestryIds: [ancestryIds.goblin] },
		{ value: "Hill Giant", ancestryIds: [ancestryIds.giant] },
		{ value: "Stone Giant", ancestryIds: [ancestryIds.giant] },
		{ value: "Lightfoot Halfling", ancestryIds: [ancestryIds.halfling] },
		{ value: "Stout Halfling", ancestryIds: [ancestryIds.halfling] },
		{ value: "Human-Raised Half-Elf", ancestryIds: [ancestryIds.halfElf] },
		{ value: "Elf-Raised Half-Elf", ancestryIds: [ancestryIds.halfElf] },
		{ value: "Marsh Lizardfolk", ancestryIds: [ancestryIds.lizardfolk] },
		{ value: "River Lizardfolk", ancestryIds: [ancestryIds.lizardfolk] },
		{ value: "Iron Orc", ancestryIds: [ancestryIds.orc] },
		{ value: "Ash Orc", ancestryIds: [ancestryIds.orc] },
		{ value: "Orc-Raised Half-Orc", ancestryIds: [ancestryIds.halfOrc] },
		{ value: "Human-Raised Half-Orc", ancestryIds: [ancestryIds.halfOrc] },
		{ value: "Ash-Blooded Demonkin", ancestryIds: [ancestryIds.demonkin] },
		{ value: "Ember-Blooded Demonkin", ancestryIds: [ancestryIds.demonkin] },
	]),
	...valueRecords("sexuality", [
		{ value: "Heterosexual", weight: 45 },
		{ value: "Bisexual", weight: 20 },
		{ value: "Homosexual", weight: 15 },
		{ value: "Pansexual", weight: 8 },
		{ value: "Asexual", weight: 7 },
		{ value: "Demisexual", weight: 5 },
	]),
	...valueRecords("alignment", [
		{ value: "Lawful Good", weight: 10 },
		{ value: "Neutral Good", weight: 16 },
		{ value: "Chaotic Good", weight: 10 },
		{ value: "Lawful Neutral", weight: 13 },
		{ value: "True Neutral", weight: 18 },
		{ value: "Chaotic Neutral", weight: 13 },
		{ value: "Lawful Evil", weight: 7 },
		{ value: "Neutral Evil", weight: 7 },
		{ value: "Chaotic Evil", weight: 6 },
	]),
	...valueRecords("condition", [
		{ value: "Healthy", weight: 65 },
		{ value: "Recovering from an injury", weight: 8 },
		{ value: "Chronically fatigued", weight: 5 },
		{ value: "Hard of hearing", weight: 4 },
		{ value: "Visually impaired", weight: 3 },
		{ value: "Uses a mobility aid", weight: 3 },
		{ value: "Carries an old war wound", weight: 5 },
		{ value: "Frequently ill", weight: 3 },
		{ value: "Marked by magical exposure", weight: 4 },
	]),
	...valueRecords("background", [
		"Raised among {heritage} families, {name} learned the habits of a {profession} through patience and necessity.",
		"{name} entered the life of a {profession} after an early talent drew the attention of a local mentor.",
		"A period of hardship pushed {name} toward work as a {profession}, where a {demeanorLower} manner became an advantage.",
		"Before becoming a {profession}, {name} traveled widely and learned to adapt quickly to unfamiliar people and customs.",
		"Family expectations shaped {name}'s path into the work of a {profession}, though the choice eventually became their own.",
		"{name} began as an assistant and gradually earned recognition as a capable {profession}.",
	]),
	...valueRecords("aspirationsMotivations", [
		"Wants to become respected as one of the finest {professionPlural} in the region.",
		"Hopes to secure a safe and prosperous future for friends and family.",
		"Seeks enough influence to correct an injustice that has gone unanswered.",
		"Dreams of leaving ordinary obligations behind to pursue a life of discovery.",
		"Is motivated by a promise made to someone who is no longer present.",
		"Wants to build a lasting legacy that will outlive personal fame.",
		"Seeks knowledge that could transform the practice of their profession.",
	]),
	...valueRecords("publicPerception", [
		"Generally regarded as reliable, although somewhat {demeanorLower}.",
		"Known as a competent {profession} whose judgment is usually trusted.",
		"Well liked by acquaintances but viewed cautiously by strangers.",
		"Respected for professional skill more than personal warmth.",
		"Considered approachable and useful in a crisis.",
		"Rumored to know more about local affairs than they openly admit.",
	]),
	...valueRecords("hiddenDetails", [
		"Secretly owes a substantial favor to a dangerous person.",
		"Keeps evidence of a past mistake that could damage their reputation.",
		"Maintains a hidden correspondence with someone across a political divide.",
		"Possesses an heirloom whose true importance has not yet been discovered.",
		"Quietly supports a cause that conflicts with their public duties.",
		"Has recurring dreams connected to a place they have never visited.",
		"Knows the truth behind a local rumor but fears the consequences of speaking.",
		"Uses their ordinary profession to conceal a second, unofficial responsibility.",
	]),
];

export const npcProfileDefaultBundles = [
	{
		generatorType: "npc",
		sectionId: "npc.profile.age-ranges",
		version: 1,
		records: npcAgeRangeDefaults,
	},
	...([
		"nickname",
		"heritage",
		"sexuality",
		"alignment",
		"condition",
		"background",
		"aspirationsMotivations",
		"publicPerception",
		"hiddenDetails",
	] as const).map((field) => ({
		generatorType: "npc",
		sectionId: `npc.profile.${field}`,
		version: 1,
		records: npcProfileValueDefaults.filter((record) => record.field === field),
	})),
] satisfies readonly DefaultCatalogBundle[];
