export { default as CitiesPage } from "./CitiesPage/CitiesPage";
export { default as CountriesPage } from "./CountriesPage/CountriesPage";
export { default as ErrorPage } from "./ErrorPage/ErrorPage";
export { default as HomePage } from "./HomePage/HomePage";
export { default as ReligionsPage } from "./ReligionsPage/ReligionsPage";
export { default as Settings } from "./Settings/Settings";
export { default as Tags } from "./Tags/Tags";
export { default as CityView } from "./ViewingPages/city";
export { default as CountryView } from "./ViewingPages/country";
export { default as ReligionsView } from "./ViewingPages/religion";
// export { default as TagsView } from './ViewingPages/tag';
export { default as ExportPage } from "./ExportPage/export";
