import { createMustacheMarkdownBlock } from "../../../../builder/mustacheBlock";

const template = [
	"# `=this.Name`",
	"",
	"> [!overview]- Overview",
	"High-level summary of the faith and its core identity.",
	"",
	"> [!Religion]- Doctrine & Beliefs",
	"Deities/domains, tenets, prohibitions, key rituals.",
	"",
	"> [!Events]- Holy Days & Observances",
	"Festivals, fasts, weekly rites, seasonal ceremonies.",
	"",
	"> [!Factions]- Organization & Sects",
	"Clergy ranks, orders, councils, schisms.",
	"",
	"> [!landmarks]- Temples & Sacred Sites",
	"Major shrines, holy cities, pilgrimage routes.",
	"",
	"> [!Items]- Relics & Iconography",
	"Sacred artifacts, symbols, colors, vestments.",
	"",
	"> [!History]- Origins & Growth",
	"Founding myths, historical turning points, reforms.",
	"",
	"> [!Regions]- Spread & Influence",
	"Where it’s practiced, allies/rivals, cultural impact.",
	"",
	"> [!lore]- Myths & Stories",
	"Creation tales, saintly legends, miracle accounts.",
	"",
	"> [!Rumors]- Heresies & Whispered Claims",
	"Controversial teachings, disputed miracles, hidden texts.",
	"",
	"> [!Secrets]- GM Notes",
	"Hidden doctrines, concealed agendas, forbidden rites.",
	"",
	"> [!Notes]- Notes",
	"Scratchpad for extra details or references.",
].join("\n");

export const botiReligionMainContentBlock = createMustacheMarkdownBlock({
	id: "boti.religion.mainContent",
	template,
});
